### ISSUE TITLE
Can't install using composer

### ISSUE THREAD

**Issue by dennis-8** [jtclark/monolog-viewer#1]
Hi,

I tried to install your package, but had the error:

> [InvalidArgumentException]
>   Could not find package jtclark/monolog-viewer at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

**Comment by jtclark** [comment]
Try this:
composer require jtclark/monolog-viewer @dev

**Comment by dennis-8** [comment]
This worked, thank you.

P.S. Maybe this should be on the readme page.
